services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: citcom_development
    ports:
      - "5432:5432"

  citcom:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ~/.irb_history:/root/.irb_history
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/citcom_development

volumes:
  postgres_data:
